server.port=${SERVER_PORT:8083}
logging.level.com=INFO
spring.application.name=ledger
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:ledgerService}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.casino.event
spring.kafka.consumer.properties.spring.json.type.mapping=betPlaced:com.casino.event.BetPlaced,betplaced:com.casino.event.BetPlaced,betSettled:com.casino.event.BetSettled,betsettled:com.casino.event.BetSettled,depositCompleted:com.casino.event.DepositCompleted,depositcompleted:com.casino.event.DepositCompleted,withdrawalProcessed:com.casino.event.WithdrawalProcessed,withdrawalprocessed:com.casino.event.WithdrawalProcessed
spring.kafka.producer.properties.max.block.ms=2000
spring.kafka.producer.retries=0

spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
spring.flyway.enabled=true
spring.flyway.locations=classpath:db.migration
spring.flyway.baseline-on-migrate=true
