spring.application.name=auth-service
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/authservice_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

logging.level.com.casino=INFO

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.instance.preferIpAddress=true
eureka.instance.preferIpAddress=true

# Base64-encoded 256-bit key for HS256 (override in production)
jwt.secret=K7gNU3sdo4LER9GjjmemsGerhHwJh4aQHKjjjZVwzVXo=
