spring.application.name=bonus

server.port=8084

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.preferIpAddress=true

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=bonus-group
spring.kafka.consumer.auto-offset-reset=earliest

# Update these lines to use the ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# This tells Spring to ignore the "type" headers sent by the producer and just map to your class
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.casino.bonus.BetPlaced