CREATE TABLE IF NOT EXISTS ledgerentrytypes (
    code INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

INSERT INTO ledgerentrytypes (code, name)
VALUES
    (1, 'Player Deposit Funds'),
    (2, 'Player Withdraw Funds'),
    (3, 'Player Bet'),
    (4, 'Player Loss'),
    (5, 'Player Win')
    ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

CREATE TABLE IF NOT EXISTS ledgerentries (
    entry_id INTEGER PRIMARY KEY,
    player_profile_id INTEGER NOT NULL,
    type INTEGER NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    created_date DATE NOT NULL,
    CONSTRAINT fk_ledgerentries_type
    FOREIGN KEY (type) REFERENCES ledgerentrytypes (code)
);

DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'ledgerentries'
              AND column_name = 'entry_id'
              AND is_identity = 'NO'
        ) THEN
            ALTER TABLE ledgerentries
                ALTER COLUMN entry_id ADD GENERATED BY DEFAULT AS IDENTITY;
        END IF;
    END $$;