package com.casino.dto;

public enum EligibilityBlockReason {
    AGE_NOT_VERIFIED,
    SELF_EXCLUDED,
    HIGH_RISK_PROFILE,
    CRITICAL_RISK_PROFILE,
    AML_REVIEW_REQUIRED,
    BETTING_LIMIT_REACHED,
    DEPOSIT_LIMIT_REACHED,
    WITHDRAWAL_REVIEW_REQUIRED,
    ACCOUNT_SUSPENDED,
    COMPLIANCE_PROFILE_NOT_FOUND
}