### Swagger UI (open in browser — Springdoc 3 serves UI here)
GET http://localhost:8086/swagger-ui/index.html

### OpenAPI JSON
GET http://localhost:8086/v3/api-docs

##############################
### Profiles API
##############################

### Create player profile
POST http://localhost:8086/profiles
content-type: application/json

{
  "accountId": "acc-106",
  "fullName": "Test Player",
  "dateOfBirth": "1999-04-15",
  "status": "ACTIVE",
  "email": "test.player@example.com",
  "phone": "+3725000100",
  "address": "Tallinn",
  "language": "en",
  "currency": "EUR"
}

### Get player profile by id
GET http://localhost:8086/profiles/pp-01

### Update player profile
PUT http://localhost:8086/profiles/pp-01
content-type: application/json

{
  "accountId": "acc-104",
  "fullName": "Test Player Updated",
  "dateOfBirth": "1999-04-15",
  "status": "INACTIVE",
  "email": "updated.player@example.com",
  "phone": "+3725000100",
  "address": "Tartu",
  "language": "et",
  "currency": "EUR"
}

### Update contact details
PATCH http://localhost:8086/profiles/pp-01/contact
content-type: application/json

{
  "email": "contact.only@example.com",
  "phone": "+3725000757",
  "address": "Parnuuuuu"
}

### Update preferences
PATCH http://localhost:8086/profiles/pp-01/preferences
content-type: application/json

{
  "language": "en",
  "currency": "USD"
}

### Get profile by account id
GET http://localhost:8086/profiles/account/acc-103